# Generated by Django 5.0.2 on 2024-02-13 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_product_price_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
